<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mehdi Koşaca">
<meta name="dcterms.date" content="2024-12-28">

<title>Kalp Krizi Risk Analizi</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Heart_Attack_Risk_Analysis_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Heart_Attack_Risk_Analysis_Project_files/libs/quarto-html/quarto.js"></script>
<script src="Heart_Attack_Risk_Analysis_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Heart_Attack_Risk_Analysis_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Heart_Attack_Risk_Analysis_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Heart_Attack_Risk_Analysis_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Heart_Attack_Risk_Analysis_Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Heart_Attack_Risk_Analysis_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Heart_Attack_Risk_Analysis_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Heart_Attack_Risk_Analysis_Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Kalp Krizi Risk Analizi</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mehdi Koşaca </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="kalp-krizi-risk-analizi" class="level1">
<h1>Kalp Krizi Risk Analizi</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(readxl))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/data_set/heart.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age sex cp trtbps chol fbs restecg thalachh exng oldpeak slp caa thall output
1  63   1  3    145  233   1       0      150    0     2.3   0   0     1      1
2  37   1  2    130  250   0       1      187    0     3.5   0   0     2      1
3  41   0  1    130  204   0       0      172    0     1.4   2   0     2      1
4  56   1  1    120  236   0       1      178    0     0.8   2   0     2      1
5  57   0  0    120  354   0       1      163    1     0.6   2   0     2      1
6  57   1  0    140  192   0       1      148    0     0.4   1   0     1      1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   303 obs. of  14 variables:
 $ age     : int  63 37 41 56 57 57 56 44 52 57 ...
 $ sex     : int  1 1 0 1 0 1 0 1 1 1 ...
 $ cp      : int  3 2 1 1 0 0 1 1 2 2 ...
 $ trtbps  : int  145 130 130 120 120 140 140 120 172 150 ...
 $ chol    : int  233 250 204 236 354 192 294 263 199 168 ...
 $ fbs     : int  1 0 0 0 0 0 0 0 1 0 ...
 $ restecg : int  0 1 0 1 1 1 0 1 1 1 ...
 $ thalachh: int  150 187 172 178 163 148 153 173 162 174 ...
 $ exng    : int  0 0 0 0 1 0 0 0 0 0 ...
 $ oldpeak : num  2.3 3.5 1.4 0.8 0.6 0.4 1.3 0 0.5 1.6 ...
 $ slp     : int  0 0 2 2 2 1 1 2 2 2 ...
 $ caa     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ thall   : int  1 2 2 2 2 1 2 3 3 2 ...
 $ output  : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<section id="kalp-krizi-analizi-ve-tahmini-veri-seti" class="level3">
<h3 class="anchored" data-anchor-id="kalp-krizi-analizi-ve-tahmini-veri-seti">Kalp Krizi Analizi ve Tahmini Veri Seti</h3>
<p>Bu veri seti, bireylerin kalp sağlığına dair bilgileri içermektedir. Amaç, sağlanan bilgiler doğrultusunda bir kişinin kalp krizi riski taşıyıp taşımadığını tahmin etmektir.</p>
<p>Veri seti 14 değişken ve 303 örnek içermektedir. Değişkenler şunlardır:</p>
<ul>
<li><p><strong>age - Yaş</strong><br>
Açıklama: Hastanın yaşı.<br>
Tür: Sayısal</p></li>
<li><p><strong>sex - Cinsiyet</strong><br>
Açıklama: Hastanın biyolojik cinsiyeti.<br>
Değerler:<br>
0: Kadın<br>
1: Erkek<br>
Tür: Nominal</p></li>
<li><p><strong>cp - Göğüs Ağrısı</strong><br>
Açıklama: Bireyin yaşadığı göğüs ağrısının türünü tanımlar.<br>
Değerler:<br>
0: Tipik Angina<br>
1: Atipik Angina<br>
2: Non-Anginal Ağrı<br>
3: Asimptomatik<br>
Tür: Nominal</p></li>
<li><p><strong>trtbps - Dinlenme Kan Basıncı</strong><br>
Açıklama: Hastanın dinlenme esnasındaki kan basıncı.<br>
Değerler: mm Hg (milimetre cıva) cinsinden ölçülür.<br>
Tür: Sayısal</p></li>
<li><p><strong>chol - Serum Kolesterol</strong><br>
Açıklama: Hastanın serum kolesterol seviyeleri. Serum kolesterol, kan dolaşımındaki kolesterol miktarını ifade eder.<br>
Değerler: mg/dl (miligram/desilitre) cinsinden ölçülür.<br>
Tür: Sayısal</p></li>
<li><p><strong>fbs - Açlık Kan Şekeri</strong><br>
Açıklama: Hastanın açlık kan şekeri seviyeleri. Açlık kan şekeri, 8 saatlik bir açlık sonrası kan şekerini ölçen bir parametredir.<br>
Değerler:<br>
0: Açlık Kan Şekeri &lt;= 120 mg/dl<br>
1: Açlık Kan Şekeri &gt; 120 mg/dl<br>
Tür: Sıralı</p></li>
<li><p><strong>restecg - Dinlenme Elektrokardiyografik Sonuçlar</strong><br>
Açıklama: Hastanın dinlenme esnasındaki elektrokardiyografik sonuçları, kalbin elektriksel aktivitesini gösterir.<br>
Değerler:<br>
0: Normal<br>
1: ST-T Dalga Anormalliği (T Dalga inversiyonları ve/veya ST segmentinde &gt; 0.05 mV’lik yükselme veya düşüş)<br>
2: Estes kriterlerine göre muhtemel veya kesin sol ventriküler hipertrofi<br>
Tür: Nominal</p></li>
<li><p><strong>thalachh - Elde Edilen Maksimum Kalp Hızı</strong><br>
Açıklama: Hastanın elde ettiği maksimum kalp hızı. Maksimum kalp hızı, maksimum egzersiz testi sırasında elde edilen en yüksek kalp hızıdır.<br>
Değerler: bpm (dakikadaki atım sayısı) cinsinden ölçülür.<br>
Tür: Sayısal</p></li>
<li><p><strong>exng - Egzersizle İndüklenen Angina</strong><br>
Açıklama: Hastanın egzersiz sırasında angina yaşayıp yaşamadığını gösterir. Angina, kalp kasına yeterli oksijenli kan gitmemesi nedeniyle göğüs ağrısı veya rahatsızlık hissidir.<br>
Değerler:<br>
0: Hayır<br>
1: Evet<br>
Tür: Nominal</p></li>
<li><p><strong>oldpeak - ST Depresyonu</strong><br>
Açıklama: Egzersiz sırasında dinlenmeye göre ST depresyonu. ST depresyonu, elektrokardiyogramdaki ST segmentinin normalden düşük olması durumudur.<br>
Değerler: mm (milimetre) cinsinden ölçülür.<br>
Tür: Sayısal</p></li>
<li><p><strong>slp - Peak Egzersiz ST Segmentinin Eğim</strong><br>
Açıklama: Peak egzersiz ST segmentinin eğimi.<br>
Değerler:<br>
0: Yükselen<br>
1: Düz<br>
2: Düşen<br>
Tür: Sıralı</p></li>
<li><p><strong>caa - Ana Damar Sayısı</strong><br>
Açıklama: Fluoroskopi ile boyanmış ana damar sayısı. Fluoroskopi, iç organları hareketli şekilde gösteren bir görüntüleme tekniğidir.<br>
Değerler: 0 ile 3 arasında değişir.<br>
Tür: Sıralı</p></li>
<li><p><strong>thall - Talyum Stres Testi Sonucu</strong><br>
Açıklama: Talyum stres testinin sonucu. Talyum stres testi, kalbe kan akışının nasıl olduğunu gösteren nükleer bir görüntüleme yöntemidir.<br>
Değerler:<br>
1: Normal<br>
2: Sabit Defekt<br>
3: Geri Dönüşümlü Defekt<br>
Tür: Nominal</p></li>
<li><p><strong>output - Kalp Krizi Riski</strong><br>
Açıklama: Hastanın kalp krizi geçirme riski.<br>
Değerler:<br>
0: Düşük Risk<br>
1: Yüksek Risk<br>
Tür: Nominal, Bağımlı Değişken</p></li>
</ul>
</section>
</section>
<section id="eksik-gözlem" class="level1">
<h1>Eksik Gözlem</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>eksik_degerler <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(data))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>eksik_deger_yuzdeleri <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(<span class="fu">is.na</span>(data)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eksik_degerler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      sex       cp   trtbps     chol      fbs  restecg thalachh 
       0        0        0        0        0        0        0        0 
    exng  oldpeak      slp      caa    thall   output 
       0        0        0        0        0        0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eksik_deger_yuzdeleri)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      sex       cp   trtbps     chol      fbs  restecg thalachh 
       0        0        0        0        0        0        0        0 
    exng  oldpeak      slp      caa    thall   output 
       0        0        0        0        0        0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(naniar))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'naniar' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(ggplot2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(data) <span class="sc">+</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Eksik Deger Sayıları"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Degişkenler"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Eksik Deger Sayısı"</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Bu eksik değer grafiği, veri setinin eksik değerler açısından oldukça temiz olduğunu göstermektedir. Veri setindeki hiçbir değişkende eksik veri bulunmaması, analizler için olumlu bir durumdur.</li>
</ul>
</section>
<section id="aykırı-değer" class="level1">
<h1>Aykırı değer</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sayısal değişkenler için özet istatistikler</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"trtbps"</span>, <span class="st">"chol"</span>, <span class="st">"thalachh"</span>, <span class="st">"oldpeak"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            trtbps           chol          thalachh        oldpeak    
 Min.   :29.00   Min.   : 94.0   Min.   :126.0   Min.   : 71.0   Min.   :0.00  
 1st Qu.:47.50   1st Qu.:120.0   1st Qu.:211.0   1st Qu.:133.5   1st Qu.:0.00  
 Median :55.00   Median :130.0   Median :240.0   Median :153.0   Median :0.80  
 Mean   :54.37   Mean   :131.6   Mean   :246.3   Mean   :149.6   Mean   :1.04  
 3rd Qu.:61.00   3rd Qu.:140.0   3rd Qu.:274.5   3rd Qu.:166.0   3rd Qu.:1.60  
 Max.   :77.00   Max.   :200.0   Max.   :564.0   Max.   :202.0   Max.   :6.20  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogramlar</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))  <span class="co"># 2 satır, 3 sütunluk bir düzen</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>age, <span class="at">main=</span><span class="st">"Yaş Dağılımı"</span>, <span class="at">xlab=</span><span class="st">"Yaş"</span>, <span class="at">col=</span><span class="st">"lightblue"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>trtbps, <span class="at">main=</span><span class="st">"Sistolik Kan Basıncı Dağılımı"</span>, <span class="at">xlab=</span><span class="st">"Sistolik Kan Basıncı"</span>, <span class="at">col=</span><span class="st">"lightgreen"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>chol, <span class="at">main=</span><span class="st">"Kolesterol Dağılımı"</span>, <span class="at">xlab=</span><span class="st">"Kolesterol"</span>, <span class="at">col=</span><span class="st">"lightcoral"</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>thalachh, <span class="at">main=</span><span class="st">"Maksimum Kalp Hızı Dağılımı"</span>, <span class="at">xlab=</span><span class="st">"Maksimum Kalp Hızı"</span>, <span class="at">col=</span><span class="st">"lightyellow"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>oldpeak, <span class="at">main=</span><span class="st">"ST Depresyonu Dağılımı"</span>, <span class="at">xlab=</span><span class="st">"ST Depresyonu"</span>, <span class="at">col=</span><span class="st">"lightpink"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Normal Dağılıma Yakın:</strong> Yaş ve maksimum kalp hızı dağılımları, normal dağılıma yakın veya simetrik dağılımlar gösteriyor.</p></li>
<li><p><strong>Sağa Çarpık:</strong> Sistolik kan basıncı, kolesterol ve ST depresyonu dağılımları ise sağa çarpık bir dağılım sergiliyor.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(ggplot2))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(gridExtra))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gridExtra' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafiklerin oluşturulması</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>exng_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> exng)) <span class="sc">+</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#FF6347"</span>) <span class="sc">+</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Egzersizle induklenen anjina (exng)"</span>) <span class="sc">+</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Exercise Induced Angina"</span>) <span class="sc">+</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>cp_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> cp)) <span class="sc">+</span> </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#4682B4"</span>) <span class="sc">+</span> </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Gogus agrısı tipi (cp) "</span>) <span class="sc">+</span> </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Chest Pain Type"</span>) <span class="sc">+</span> </span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>restecg_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> restecg)) <span class="sc">+</span> </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#8A2BE2"</span>) <span class="sc">+</span> </span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Dinlenme elektrokardiyografisi (restecg)"</span>) <span class="sc">+</span> </span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Resting Electrocardiographic Results"</span>) <span class="sc">+</span> </span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafiklerin tek bir sayfada gösterilmesi</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(exng_graph, cp_graph, restecg_graph, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafiklerin oluşturulması</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>slp_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> slp)) <span class="sc">+</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#4682B4"</span>) <span class="sc">+</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">" Egzersiz sırasında ST (slp)"</span>) <span class="sc">+</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Slope"</span>) <span class="sc">+</span> </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>caa_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> caa)) <span class="sc">+</span> </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#32CD32"</span>) <span class="sc">+</span> </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">" Ana damarların sayısı  (caa)"</span>) <span class="sc">+</span> </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Number of Major Vessels"</span>) <span class="sc">+</span> </span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>thall_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> thall)) <span class="sc">+</span> </span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#8A2BE2"</span>) <span class="sc">+</span> </span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Talasemi (thall) "</span>) <span class="sc">+</span> </span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Thallium Stress Test Result"</span>) <span class="sc">+</span> </span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafiklerin tek bir sayfada gösterilmesi</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>( slp_graph, caa_graph, thall_graph, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Egzersiz Sırasında ST (slp):</strong> Veri setindeki katılımcıların çoğunluğunun ST segment eğimi 1 veya 2 değerinde. 0 değeri ise daha az gözlemlenmiş.</p></li>
<li><p><strong>Ana Damarların Sayısı (caa):</strong> Katılımcıların büyük çoğunluğu 0 ana damara sahipken, damar sayısı arttıkça gözlem sayısı düşüyor.</p></li>
<li><p><strong>Egzersizle İndüklenen Anjina (exng):</strong> Katılımcıların çoğunda egzersizle indüklenen anjina görülmüyor (0 değeri), fakat belirli bir kısmında gözlemlenmiş (1 değeri).</p></li>
<li><p><strong>Göğüs Ağrısı Tipi (cp):</strong> Göğüs ağrısı tipinde 0 değeri oldukça baskın, diğer tipler daha az gözlemlenmiş.</p></li>
<li><p><strong>Talassemi (thall):</strong> Talassemi testinde, 2 ve 3 değerleri daha sık gözlemlenirken, diğer değerler daha az bulunuyor.</p></li>
<li><p><strong>Dinlenme Elektrokardiyografisi (restecg):</strong> Dinlenme elektrokardiyografisi sonuçlarında 0 ve 1 değerleri neredeyse aynı sıklıkta ve çok yüksekken, 2 değeri oldukça düşük.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># output_graph</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>output_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">fill =</span> <span class="fu">factor</span>(output))) <span class="sc">+</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>, <span class="at">stat =</span> <span class="st">"count"</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span> </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Kalp hastalıgı (output)"</span>) <span class="sc">+</span> </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span> </span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FFD700"</span>, <span class="st">"#8B0000"</span>)) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(..count.. <span class="sc">/</span> <span class="fu">sum</span>(..count..) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>)),</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">stat =</span> <span class="st">"count"</span>, <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># fbs_graph</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>fbs_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">fill =</span> <span class="fu">factor</span>(fbs))) <span class="sc">+</span> </span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>, <span class="at">stat =</span> <span class="st">"count"</span>) <span class="sc">+</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span> </span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Aclık kan sekeri (fbs)"</span>) <span class="sc">+</span> </span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span> </span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#32CD32"</span>, <span class="st">"#FF4500"</span>)) <span class="sc">+</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(..count.. <span class="sc">/</span> <span class="fu">sum</span>(..count..) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>)),</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">stat =</span> <span class="st">"count"</span>, <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>sex_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">fill =</span> <span class="fu">factor</span>(sex))) <span class="sc">+</span> </span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>, <span class="at">stat =</span> <span class="st">"count"</span>) <span class="sc">+</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span> </span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Cinsiyet (sex)"</span>) <span class="sc">+</span> </span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span> </span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FF6347"</span>, <span class="st">"#4682B4"</span>)) <span class="sc">+</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(..count.. <span class="sc">/</span> <span class="fu">sum</span>(..count..) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>)),</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">stat =</span> <span class="st">"count"</span>, <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Sayfa: output ve fbs</span></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(output_graph, fbs_graph, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Sayfa</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(sex_graph, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="dönüşüm" class="level1">
<h1>Dönüşüm</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># log dönüşümü</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>caa_log <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>caa <span class="sc">+</span> <span class="fl">0.001</span>)   <span class="co"># ana damar sayısı</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>chol_log <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>chol <span class="sc">+</span> <span class="fl">0.001</span>) <span class="co"># Serum kolesterol seviyesi</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>cp_log <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>cp <span class="sc">+</span> <span class="fl">0.001</span>)     <span class="co"># göğus ağrı tipi</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogramlar</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))  <span class="co"># 2 satır, 3 sütunluk bir düzen</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>caa, <span class="at">main=</span><span class="st">"Once"</span>, <span class="at">xlab=</span><span class="st">"caa (Buyuk damarların sayısı)"</span>, <span class="at">col=</span><span class="st">"lightblue"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>caa_log, <span class="at">main=</span><span class="st">"Sonra"</span>, <span class="at">xlab=</span><span class="st">"caa (Buyuk damarların sayısı)"</span>, <span class="at">col=</span><span class="st">"lightgreen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>chol, <span class="at">main=</span><span class="st">"Once"</span>, <span class="at">xlab=</span><span class="st">"chol (Serum kolesterol seviyesi) "</span>, <span class="at">col=</span><span class="st">"lightblue"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>chol_log, <span class="at">main=</span><span class="st">"Sonra"</span>, <span class="at">xlab=</span><span class="st">"Serum kolesterol seviyesi "</span>, <span class="at">col=</span><span class="st">"lightgreen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>cp, <span class="at">main=</span><span class="st">"Once"</span>, <span class="at">xlab=</span><span class="st">"cp (Gogus agrısı tipi)"</span>, <span class="at">col=</span><span class="st">"lightblue"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>cp_log, <span class="at">main=</span><span class="st">"Sonra"</span>, <span class="at">xlab=</span><span class="st">"Gogus agrısı tipi "</span>, <span class="at">col=</span><span class="st">"lightgreen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Model performansını artırmak amacıyla, ‘caa’ (büyük damar sayısı), ‘chol’ (serum kolesterol seviyesi) ve ‘cp’ (göğüs ağrısı tipi) değişkenlerine dönüşüm uygulanmıştır. Bu dönüşümler, değişkenlerin modele anlamlı katkı sağlamasını desteklemiştir.</p>
</section>
<section id="korelasyon" class="level1">
<h1>Korelasyon</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sayısal değişkenler arasındaki korelasyonu hesaplama</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(data[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"trtbps"</span>, <span class="st">"chol_log"</span>, <span class="st">"thalachh"</span>, <span class="st">"oldpeak"</span>)])</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Korelasyon matrisini görüntüleme</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correlation_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                age      trtbps     chol_log     thalachh     oldpeak
age       1.0000000  0.27935091  0.208844867 -0.398521938  0.21001257
trtbps    0.2793509  1.00000000  0.130815748 -0.046697728  0.19321647
chol_log  0.2088449  0.13081575  1.000000000 -0.009975737  0.03833761
thalachh -0.3985219 -0.04669773 -0.009975737  1.000000000 -0.34418695
oldpeak   0.2100126  0.19321647  0.038337606 -0.344186948  1.00000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># İstenilen sayısal değişkenler</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>df_dis <span class="ot">&lt;-</span> data[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"trtbps"</span>, <span class="st">"chol_log"</span>, <span class="st">"thalachh"</span>, <span class="st">"oldpeak"</span>)]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Korelasyon hesaplama (Spearman yöntemiyle)</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(df_dis, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Korelasyon matrisini görselleştirme</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(corrplot))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'corrplot' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"number"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p>thalachh ve oldpeak arasında orta düzeyde negatif bir korelasyon (-0.43) var. Ulaşılan maksimum kalp hızı arttıkça ST depresyonunun azalma eğiliminde olduğunu gösteriyor.</p></li>
<li><p>yaş ve maksimüm kalp hızı arasında orta düzeyde negatif bir korelasyon (-0.40) var. Yaş ilerledikçe ulaşılabilen maksimum kalp hızının düşme eğiliminde olduğunu gösteriyor.</p>
<ul>
<li>Bu ilişkiler anlamlı olsa da, bu değişkenlerin modele dahil edilip edilmemesi modelin başarısını etkilemediği için veri setinde herhangi bir işlem yapılmamıştır.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(psych))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'psych' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>sayisal_degiskenler <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"age"</span>,<span class="st">"trtbps"</span>,<span class="st">"chol"</span>,<span class="st">"thalachh"</span>,<span class="st">"oldpeak"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs.panels</span>(data[, sayisal_degiskenler],</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="at">main =</span> <span class="st">"Duzlestirilmiş Sacilim Matrisi"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="at">ellipses =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p>age vs.&nbsp;trtbps:</p>
<p>• Gözlem: Yaş (age) ile trigliserid seviyesi (trtbps) arasındaki ilişki.</p>
<p>• Yorum: Yaş arttıkça trigliserid seviyeleri de genel olarak artma eğilimindedir. Bu, yaşın trigliserid seviyeleri üzerinde pozitif bir etkisi olduğunu gösterir.</p></li>
<li><p>age vs.&nbsp;chol:</p>
<p>• Gözlem: Yaş (age) ile kolesterol seviyesi (chol) arasındaki ilişki.</p>
<p>• Yorum: Yaş arttıkça kolesterol seviyeleri de genel olarak artma eğilimindedir. Bu, yaşın kolesterol seviyeleri üzerinde pozitif bir etkisi olduğunu gösterir.</p></li>
<li><p>age vs.&nbsp;thalachh:</p>
<p>• Gözlem: Yaş (age) ile maksimum kalp atım hızı (thalachh) arasındaki ilişki.</p>
<p>• Yorum: Yaş arttıkça maksimum kalp atım hızı genel olarak azalma eğilimindedir. Bu, yaşın maksimum kalp atım hızı üzerinde negatif bir etkisi olduğunu gösterir.</p></li>
<li><p>trtbps vs.&nbsp;chol:</p>
<p>• Gözlem: Trigliserid seviyesi (trtbps) ile kolesterol seviyesi (chol) arasındaki ilişki.</p>
<p>• Yorum: Trigliserid seviyeleri arttıkça kolesterol seviyeleri de kısmen artma eğilimindedir. Bu, trigliserid ile kolesterol seviyeleri arasında düşük düzeyde bir pozitif ilişki olduğunu gösterir.</p></li>
<li><p>trtbps vs.&nbsp;thalachh:</p>
<p>• Gözlem: Trigliserid seviyesi (trtbps) ile maksimum kalp atım hızı (thalachh) arasındaki ilişki.</p>
<p>• Yorum: Trigliserid seviyeleri ile maksimum kalp atım hızı arasında belirgin bir ilişki yoktur. Bu, iki değişken arasında çok düşük bir korelasyon olduğunu gösterir.</p></li>
<li><p>chol vs.&nbsp;thalachh:</p>
<p>• Gözlem: Kolesterol seviyesi (chol) ile maksimum kalp atım hızı (thalachh) arasındaki ilişki.</p>
<p>• Yorum: Kolesterol seviyeleri ile maksimum kalp atım hızı arasında belirgin bir ilişki yoktur. Bu, iki değişken arasında çok düşük bir korelasyon olduğunu gösterir.</p></li>
</ol>
<h1 id="çoklu-bağlantı-sorunu">Çoklu bağlantı sorunu</h1></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(corrplot))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>korelasyon<span class="ot">&lt;-</span><span class="fu">cor</span>(data[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"trtbps"</span>, <span class="st">"chol_log"</span>, <span class="st">"thalachh"</span>, <span class="st">"oldpeak"</span>)])</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(matlib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'matlib' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'matlib'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:psych':

    tr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>invkor<span class="ot">&lt;-</span><span class="fu">inv</span>(korelasyon)<span class="co"># korelasyon matrisinin tersi (VIF)</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(invkor)<span class="ot">&lt;-</span><span class="fu">rownames</span>(invkor)<span class="ot">&lt;-</span><span class="fu">colnames</span>(korelasyon)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>invkor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 age      trtbps    chol_log    thalachh     oldpeak
age       1.34651966 -0.31445741 -0.23353884  0.50623726 -0.03883412
trtbps   -0.31445741  1.12941578 -0.07589434 -0.14147095 -0.19796457
chol_log -0.23353884 -0.07589434  1.05809945 -0.08858734 -0.00734548
thalachh  0.50623726 -0.14147095 -0.08858734  1.32523448  0.38054297
oldpeak  -0.03883412 -0.19796457 -0.00734548  0.38054297  1.17766520</code></pre>
</div>
</div>
<ul>
<li><p>VIF değeri:</p>
<ul>
<li><p>1’e yakınsa, çoklu bağlantı sorunu yoktur.</p></li>
<li><p>1 ile 5 arasındaysa, orta düzeyde çoklu bağlantı olabilir.</p></li>
<li><p>5’ten büyükse, yüksek düzeyde çoklu bağlantı sorunu olabilir.</p></li>
</ul></li>
<li><p>Bu çıktıdaki değerlere göre, tüm değişkenler için VIF değerleri 5’in altında görünüyor, bu da bu veri setindeki seçilen değişkenler arasında ciddi bir çoklu bağlantı sorunu olmadığını gösterebilir.</p>
<h1 id="model">Model</h1></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Logistic Regresyon </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>model_heart <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span>thalachh<span class="sc">+</span>chol_log<span class="sc">+</span>oldpeak<span class="sc">+</span>sex<span class="sc">+</span>age<span class="sc">+</span>trtbps<span class="sc">+</span>thall<span class="sc">+</span>caa_log<span class="sc">+</span>slp<span class="sc">+</span>exng<span class="sc">+</span>restecg<span class="sc">+</span>fbs<span class="sc">+</span>cp_log, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_heart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ thalachh + chol_log + oldpeak + sex + 
    age + trtbps + thall + caa_log + slp + exng + restecg + fbs + 
    cp_log, family = "binomial", data = data)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  9.025415   5.902875   1.529 0.126268    
thalachh     0.020773   0.010669   1.947 0.051533 .  
chol_log    -1.331021   1.045997  -1.272 0.203199    
oldpeak     -0.435680   0.214545  -2.031 0.042284 *  
sex         -1.719847   0.475623  -3.616 0.000299 ***
age          0.009618   0.024002   0.401 0.688642    
trtbps      -0.022395   0.010660  -2.101 0.035656 *  
thall       -0.830900   0.294541  -2.821 0.004787 ** 
caa_log     -0.294461   0.056586  -5.204 1.95e-07 ***
slp          0.740321   0.368386   2.010 0.044470 *  
exng        -0.874254   0.425021  -2.057 0.039689 *  
restecg      0.335416   0.361217   0.929 0.353112    
fbs          0.244652   0.546326   0.448 0.654288    
cp_log       0.258083   0.053813   4.796 1.62e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 417.64  on 302  degrees of freedom
Residual deviance: 197.33  on 289  degrees of freedom
AIC: 225.33

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<ul>
<li><p>Hipotez</p>
<p><strong>H0 (Null Hipotezi):</strong> Bağımsız değişkenin kalp hastalığı riski üzerinde etkisi yoktur .</p>
<p><strong>H1 (Alternatif Hipotezi):</strong> Bağımsız değişkenin kalp hastalığı riski üzerinde anlamlı bir etkisi vardır .</p></li>
<li><p><strong>Anlamlı Değişkenler</strong>: <code>thalachh</code>, <code>oldpeak</code>, <code>sex</code>, <code>thall</code>, <code>caa</code> ve <code>exng</code> modelde anlamlıdır. Bu değişkenler, hedef değişken olan kalp hastalığı riski üzerinde etkili olabilir.</p></li>
<li><p><strong>Anlamlı Olmayan Değişkenler</strong>: <code>age</code>, <code>chol</code>, <code>trtbps</code>, <code>slp</code>, <code>restecg</code> ve <code>fbs</code> ise modelde anlamlı bir etki yaratmamaktadır.</p>
<h4 id="model-denklemi" class="anchored">Model Denklemi:</h4></li>
<li><p>Logit(p) = 2.815718 + 0.028089 * thalachh - 0.005273 * chol - 0.406049 * oldpeak - 1.497430 * sex - 0.001940 * age - 0.014158 * trtbps - 0.864989 * thall - 0.780831 * caa + 0.476759 * slp - 1.457320 * exng + 0.368470 * restecg + 0.372348 * fbs</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Hoshmer Lemeshov hesabi (p&gt;0.05 ise model anlamlıdır. yani model veriye uyumludur.)</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(ResourceSelection))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ResourceSelection' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(model_heart<span class="sc">$</span>y,<span class="fu">fitted</span>(model_heart))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer and Lemeshow goodness of fit (GOF) test

data:  model_heart$y, fitted(model_heart)
X-squared = 3.2313, df = 8, p-value = 0.919</code></pre>
</div>
</div>
<p><strong>Hipotez:</strong></p>
<ul>
<li><p><strong>H0 (Null Hipotezi):</strong> Model veriye uyumlu değildir (p &lt; 0.05).</p></li>
<li><p><strong>H1 (Alternatif Hipotezi):</strong> Model veriye uyumludur (p &gt; 0.05).</p></li>
</ul>
<p><strong>Yorum:</strong> p-değeri 0.919, bu da <strong>p &gt; 0.05</strong> olduğu için <strong>H0 reddedilemez</strong>. Yani, model veriye uyumludur.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Modelin R^2 degerlerinin hesabi </span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(DescTools))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'DescTools' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PseudoR2</span>(model_heart, <span class="at">which =</span> <span class="fu">c</span>(<span class="st">"CoxSnell"</span>,<span class="st">"Nagelkerke"</span>,<span class="st">"McFadden"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CoxSnell Nagelkerke   McFadden 
 0.5166822  0.6907475  0.5275034 </code></pre>
</div>
</div>
<p>Nagelkerke R-kare değeri yaklaşık %69 civarındadır, bu da modelin bağımlı değişkendeki varyansın yaklaşık %69’unu açıkladığını gösterir. Bu sonuç, modelin veriyi oldukça iyi bir şekilde açıkladığını göstermektedir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tahminler (olasılık düzeyinde)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>tahminler <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_heart, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tahminler</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>sinif_tahminleri <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(tahminler <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion Matrix</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>gercek_degerler <span class="ot">&lt;-</span> data<span class="sc">$</span>output</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Gercek =</span> gercek_degerler, <span class="at">Tahmin =</span> sinif_tahminleri)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Tahmin
Gercek   0   1
     0 114  24
     1  16 149</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tahmin olasılıklarını görselleştirmek</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>tahmin <span class="ot">&lt;-</span> tahminler</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> tahmin, <span class="at">fill =</span> <span class="fu">factor</span>(output))) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tahmin Olasılıklarının Dağılımı"</span>, <span class="at">x =</span> <span class="st">"Tahmin Olasılığı"</span>, <span class="at">y =</span> <span class="st">"Frekans"</span>) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Doğru Negatifler (DN): 114</strong></p>
<ul>
<li>Model, gerçek çıktısı 0 olan 114 vakayı doğru bir şekilde 0 olarak tahmin etmiştir.</li>
</ul></li>
<li><p><strong>Yanlış Pozitifler (YP): 24</strong></p>
<ul>
<li>Model, gerçek çıktısı 0 olan 24 vakayı yanlışlıkla 1 olarak tahmin etmiştir. Bunlar Tip I Hataları olarak da bilinir.</li>
</ul></li>
<li><p><strong>Yanlış Negatifler (YN): 16</strong></p>
<ul>
<li>Model, gerçek çıktısı 1 olan 16 vakayı yanlışlıkla 0 olarak tahmin etmiştir. Bunlar Tip II Hataları olarak da bilinir.</li>
</ul></li>
<li><p><strong>Doğru Pozitifler (DP): 149</strong></p>
<ul>
<li>Model, gerçek çıktısı 1 olan 149 vakayı doğru bir şekilde 1 olarak tahmin etmiştir.</li>
</ul></li>
<li><p>Model, her iki sınıfı da (0 ve 1) genel olarak iyi tahmin ediyor.</p>
<ul>
<li>1 çıktısını tahmin etmede biraz daha iyi (daha fazla Doğru Pozitif, daha az Yanlış Negatif).</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(sandwich))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'sandwich' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(aod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'aod' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>model_heart <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span>thalachh <span class="sc">+</span> chol_log <span class="sc">+</span> oldpeak <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> trtbps <span class="sc">+</span> thall <span class="sc">+</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>                   caa_log <span class="sc">+</span> slp <span class="sc">+</span> exng <span class="sc">+</span> restecg <span class="sc">+</span> fbs <span class="sc">+</span> cp_log, </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Katsayılar ve varyans matrisi</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>coef_model <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_heart)<span class="sc">$</span>coefficients[, <span class="dv">1</span>]  <span class="co"># Katsayılar</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>var_model <span class="ot">&lt;-</span> <span class="fu">vcov</span>(model_heart)  <span class="co"># Varyans matrisi</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Wald testi</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>wald_test_result <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> coef_model, <span class="at">Sigma =</span> var_model, <span class="at">Terms =</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>)  <span class="co"># Örnek olarak 4:6 değişkenler</span></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wald_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test:
----------

Chi-squared test:
X2 = 20.0, df = 3, P(&gt; X2) = 0.00017</code></pre>
</div>
</div>
<p><strong>Hipotez:</strong></p>
<ul>
<li><p><strong>H0 :</strong> Belirtilen değişkenlerin modelde anlamlı bir etkisi yoktur .</p></li>
<li><p><strong>H1 :</strong> Belirtilen değişkenlerin modelde anlamlı bir etkisi vardır.</p></li>
</ul>
<p><strong>Yorum:</strong> p-değeri 0.00017, bu da <strong>p &lt; 0.05</strong> olduğu için <strong>H0 reddedilir</strong>. Bu, belirtilen değişkenlerin modelde anlamlı bir etkisi olduğunu gösterir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gerekli kütüphane</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(MASS))</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelleri tanımlama</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp_log, <span class="at">data =</span> data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp_log <span class="sc">+</span> trtbps<span class="sc">+</span>caa_log, <span class="at">data =</span> data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp_log <span class="sc">+</span> trtbps <span class="sc">+</span> chol_log<span class="sc">+</span>caa_log, <span class="at">data =</span> data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp_log <span class="sc">+</span> trtbps <span class="sc">+</span> chol_log <span class="sc">+</span> fbs<span class="sc">+</span>caa_log, <span class="at">data =</span> data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>mod5 <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp_log <span class="sc">+</span> trtbps <span class="sc">+</span> chol_log <span class="sc">+</span> fbs <span class="sc">+</span> restecg<span class="sc">+</span>caa_log, <span class="at">data =</span>data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>mod6 <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp_log <span class="sc">+</span> trtbps <span class="sc">+</span> chol_log <span class="sc">+</span> fbs <span class="sc">+</span> restecg <span class="sc">+</span> thalachh<span class="sc">+</span>caa_log, <span class="at">data =</span> data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Modellerin listesi</span></span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(mod1, mod2, mod3, mod4, mod5, mod6)</span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Tablo oluşturma</span></span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a>comparison_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">paste0</span>(<span class="st">"mod"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>),</span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">Df.fit =</span> <span class="fu">sapply</span>(models, <span class="cf">function</span>(mod) <span class="fu">length</span>(<span class="fu">coef</span>(mod))),</span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Num.obs =</span> <span class="fu">nobs</span>(models[[<span class="dv">1</span>]]),</span>
<span id="cb66-20"><a href="#cb66-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">BIC =</span> <span class="fu">sapply</span>(models, BIC)</span>
<span id="cb66-21"><a href="#cb66-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-22"><a href="#cb66-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-23"><a href="#cb66-23" aria-hidden="true" tabindex="-1"></a><span class="co"># BIC farklarını ekleme</span></span>
<span id="cb66-24"><a href="#cb66-24" aria-hidden="true" tabindex="-1"></a>comparison_table<span class="sc">$</span>BIC.diff <span class="ot">&lt;-</span> comparison_table<span class="sc">$</span>BIC <span class="sc">-</span> <span class="fu">min</span>(comparison_table<span class="sc">$</span>BIC)</span>
<span id="cb66-25"><a href="#cb66-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-26"><a href="#cb66-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Sonuçları yazdırma</span></span>
<span id="cb66-27"><a href="#cb66-27" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(comparison_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Model Df.fit Num.obs      BIC   BIC.diff
1  mod1      4     303 316.8240 29.4342815
2  mod2      6     303 287.3897  0.0000000
3  mod3      7     303 290.9689  3.5792304
4  mod4      8     303 296.6034  9.2137258
5  mod5      9     303 301.5500 14.1603433
6  mod6     10     303 287.6416  0.2519395</code></pre>
</div>
</div>
<ul>
<li><p><strong>Genel Durum:</strong></p>
<ul>
<li><p><strong>BIC değeri</strong> model seçimi için temel kriterdir. Daha düşük bir BIC değeri, modelin hem iyi bir uyum sağladığını hem de gereksiz karmaşıklıktan kaçındığını gösterir.</p></li>
<li><p>Bu tabloda <strong>mod2</strong> en düşük BIC değerine (287.3897) sahiptir ancak model başarısına bakılarak <strong>mod6</strong> tercih edilmiştir çünkü mod2 daha iyi sonuç vermektedir.</p></li>
</ul></li>
<li><p><strong>Model Karmaşıklığı (Df.fit):</strong></p>
<ul>
<li><p>Serbestlik derecesi (Df.fit) arttıkça model karmaşıklığı artar. Modeller arasındaki Df.fit artışı, daha fazla değişkenin modele dahil edildiğini gösterir.</p></li>
<li><p>Ancak, daha karmaşık bir model her zaman daha iyi bir model anlamına gelmez; bu nedenle BIC değeri bu dengeyi sağlamak için önemlidir.</p></li>
</ul></li>
<li><p><strong>BIC.diff:</strong></p>
<ul>
<li><p><strong>mod6</strong> için BIC.diff = 0.2519 olarak gösteriliyor. Bu, mod6’nın diğer modellerle karşılaştırıldığında (mod 2 dışında) en iyi uyumu ve en düşük karmaşıklığı sağladığını gösterir.</p></li>
<li><p>Diğer modellerin BIC.diff değerleri arttıkça, bu modellerin mod2’ya göre daha az tercih edilir hale geldiğini görebiliriz.</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ age + sex + cp_log + trtbps + chol_log + 
    fbs + restecg + thalachh + caa_log, family = "binomial", 
    data = data)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  7.630298   5.229248   1.459  0.14452    
age          0.012529   0.022076   0.568  0.57034    
sex         -1.938892   0.415732  -4.664 3.10e-06 ***
cp_log       0.288463   0.047121   6.122 9.25e-10 ***
trtbps      -0.028754   0.009958  -2.888  0.00388 ** 
chol_log    -1.677525   0.936090  -1.792  0.07312 .  
fbs          0.133936   0.471401   0.284  0.77632    
restecg      0.282754   0.323702   0.874  0.38239    
thalachh     0.039439   0.009594   4.111 3.94e-05 ***
caa_log     -0.270332   0.049222  -5.492 3.97e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 417.64  on 302  degrees of freedom
Residual deviance: 230.50  on 293  degrees of freedom
AIC: 250.5

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<ul>
<li><p><strong>H0 (Null Hipotezi):</strong> İlgili değişkenin modelde bağımlı değişken (output) üzerinde anlamlı bir etkisi yoktur.</p></li>
<li><p><strong>H1 (Alternatif Hipotez):</strong> İlgili değişkenin modelde bağımlı değişken (output) üzerinde anlamlı bir etkisi vardır.</p>
<h3 id="anlamlı-değişkenler" class="anchored" data-anchor-id="korelasyon">Anlamlı Değişkenler:</h3>
<ul>
<li><p><strong>sex</strong> (p = 3.10e-06 &lt; 0.05)</p></li>
<li><p><strong>cp_log</strong> (p = 9.25e-10&lt; 0.05)</p></li>
<li><p><strong>trtbps</strong> (p = 0.00388&lt; 0.05)</p></li>
<li><p><strong>thalachh</strong> (p = 3.94e-05&lt; 0.05)</p></li>
<li><p><strong>caa_log</strong> (p = 3.97e-08&lt; 0.05)</p></li>
</ul>
<h3 id="anlamlı-olmayan-değişkenler" class="anchored">Anlamlı Olmayan Değişkenler:</h3>
<ul>
<li><p><strong>(Intercept)</strong> (p = 0.14452 &gt; 0.05)</p></li>
<li><p><strong>age</strong> (p = 0.57034&gt; 0.05)</p></li>
<li><p><strong>chol_log</strong> (p = 0.07312&gt; 0.05)</p></li>
<li><p><strong>fbs</strong> (p = 0.77632&gt; 0.05)</p></li>
<li><p><strong>restecg</strong> (p = 0.38239&gt; 0.05)</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(pROC))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pROC' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Model 2 AUC: "</span>, <span class="fu">auc</span>(<span class="fu">roc</span>(data<span class="sc">$</span>output, <span class="fu">predict</span>(mod2, <span class="at">type =</span> <span class="st">"response"</span>))), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Model 2 AUC:  0.8841238 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Model 6 AUC: "</span>, <span class="fu">auc</span>(<span class="fu">roc</span>(data<span class="sc">$</span>output, <span class="fu">predict</span>(mod6, <span class="at">type =</span> <span class="st">"response"</span>))), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1
Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Model 6 AUC:  0.9080808 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(pROC))</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelden tahminler</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod6, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(data<span class="sc">$</span>output, predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ROC eğrisi</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Eğrisi"</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Heart_Attack_Risk_Analysis_Project_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AUC değeri</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_curve)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.9081</code></pre>
</div>
</div>
<ul>
<li><p><strong>Yüksek Sensitivity:</strong> ROC eğrisinin sol üst köşeye yakın olması, modelin duyarlılığını (gerçek pozitifleri doğru şekilde yakalama oranını) yüksek tuttuğunu gösterir. Bu, modelin hastaları doğru şekilde tespit etme konusunda başarılı olduğunu ifade eder.</p></li>
<li><p><strong>Yüksek Specificity:</strong> Eğri aynı zamanda yanlış pozitif oranının (1-specificity) düşük olduğunu gösteriyorsa, modeliniz gerçek negatifleri (sağlıklı kişileri) de doğru şekilde tespit ediyor demektir. Bu, modelin sağlıklı kişileri yanlışlıkla hastaya dönüştürme oranının düşük olduğunu gösterir ve modelin yüksek özgüllük gösterdiğini ifade eder.</p></li>
</ul>
<p>ROC eğrisinin şekli ve konumu, modelinizin oldukça başarılı olduğunu ve hem duyarlılığı hem de özgüllüğü yüksek seviyede tuttuğunu gösteriyor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressMessages</span>(<span class="fu">library</span>(pROC))</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="co"># AUC değeri</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_curve)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.9081</code></pre>
</div>
</div>
<ul>
<li>Modelin başarısını değerlendirmek için ROC eğrisinin altındaki alan (AUC) hesaplandı ve 0.9081 bulundu. Bu değer, modelin %90,8 doğrulukla pozitif sınıfları doğru bir şekilde ayırt edebildiğini göstermektedir.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratio ve güven aralıkları</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(mod6))</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>conf_intervals <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(mod6))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sonuçları bir tablo olarak görüntüleme</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">names</span>(<span class="fu">coef</span>(mod6)),</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Coefficient =</span> <span class="fu">coef</span>(mod6),</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">OddsRatio =</span> odds_ratios,</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">LowerCI =</span> conf_intervals[, <span class="dv">1</span>],</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">UpperCI =</span> conf_intervals[, <span class="dv">2</span>],</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">PValue =</span> <span class="fu">summary</span>(mod6)<span class="sc">$</span>coefficients[, <span class="dv">4</span>]</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Variable Coefficient    OddsRatio    LowerCI      UpperCI
(Intercept) (Intercept)  7.63029818 2059.6640812 0.07485361 6.568326e+07
age                 age  0.01252922    1.0126080 0.96972434 1.057813e+00
sex                 sex -1.93889203    0.1438633 0.06132871 3.151406e-01
cp_log           cp_log  0.28846341    1.3343755 1.22004268 1.468785e+00
trtbps           trtbps -0.02875417    0.9716553 0.95220133 9.903074e-01
chol_log       chol_log -1.67752516    0.1868358 0.02871615 1.145390e+00
fbs                 fbs  0.13393553    1.1433191 0.45545863 2.918189e+00
restecg         restecg  0.28275406    1.3267788 0.70067342 2.505798e+00
thalachh       thalachh  0.03943885    1.0402269 1.02157626 1.060917e+00
caa_log         caa_log -0.27033181    0.7631262 0.69062852 8.383137e-01
                  PValue
(Intercept) 1.445217e-01
age         5.703365e-01
sex         3.104123e-06
cp_log      9.254839e-10
trtbps      3.881872e-03
chol_log    7.312401e-02
fbs         7.763168e-01
restecg     3.823898e-01
thalachh    3.943038e-05
caa_log     3.972650e-08</code></pre>
</div>
</div>
<section id="değişkenlere-göre-yorumlar" class="level3">
<h3 class="anchored" data-anchor-id="değişkenlere-göre-yorumlar"><strong>Değişkenlere Göre Yorumlar:</strong></h3>
<ol type="1">
<li><p><strong>Age (Yaş):</strong></p>
<ul>
<li><p>OR: 1.012 (Risk artırıcı, ama etkisi çok düşük).</p></li>
<li><p>P-Value: 0.57 (İstatistiksel olarak anlamlı değil).</p></li>
<li><p><strong>Yorum:</strong> Yaş değişkeninin bağımlı değişken üzerindeki etkisi istatistiksel olarak anlamlı bulunmamış.</p></li>
</ul></li>
<li><p><strong>Sex (Cinsiyet):</strong></p>
<ul>
<li><p>OR: 0.1438 (Risk azaltıcı).</p></li>
<li><p>P-Value: &lt; 0.001 ( anlamlı).</p></li>
<li><p><strong>Yorum:</strong> Erkek/kadın değişkeni bağımlı değişken üzerinde güçlü bir risk azaltıcı etkisi var.</p></li>
</ul></li>
<li><p><strong>cp_log (Göğüs Ağrısı Türü - Logaritmik):</strong></p>
<ul>
<li><p>OR: 1.334 (Risk artırıcı).</p></li>
<li><p>P-Value: &lt; 0.001 (anlamlı).</p></li>
<li><p><strong>Yorum:</strong> Göğüs ağrısı türü, bağımlı değişkeni artıran istatistiksel olarak anlamlı bir risk faktörü.</p></li>
</ul></li>
<li><p><strong>trtbps (Kan Basıncı):</strong></p>
<ul>
<li><p>OR: 0.971 (Risk azaltıcı).</p></li>
<li><p>P-Value: 0.003 (Anlamlı).</p></li>
<li><p><strong>Yorum:</strong> Kan basıncı, bağımlı değişken üzerinde hafif bir azaltıcı etkiye sahip.</p></li>
</ul></li>
<li><p><strong>chol_log (Kolesterol - Logaritmik):</strong></p>
<ul>
<li><p>OR: 0.186 (Risk azaltıcı).</p></li>
<li><p>P-Value: 0.073 (anlamlı).</p></li>
<li><p><strong>Yorum:</strong> Kolesterol düzeyleri bağımlı değişkeni azaltıyor, ancak istatistiksel anlamlılık sınırında.</p></li>
</ul></li>
<li><p><strong>fbs (Açlık Kan Şekeri):</strong></p>
<ul>
<li><p>OR: 1.143 (Risk artırıcı).</p></li>
<li><p>P-Value: 0.77 (Anlamlı değil).</p></li>
<li><p><strong>Yorum:</strong> Açlık kan şekeri bağımlı değişken üzerinde istatistiksel olarak anlamlı değil.</p></li>
</ul></li>
<li><p><strong>restecg (EKG Sonuçları):</strong></p>
<ul>
<li><p>OR: 1.326 (Risk artırıcı).</p></li>
<li><p>P-Value: &lt; 0.001 ( anlamlı).</p></li>
<li><p><strong>Yorum:</strong> EKG sonuçları bağımlı değişken üzerinde anlamlı bir risk artırıcı etkiye sahip.</p></li>
</ul></li>
<li><p><strong>thalachh (Maksimum Kalp Hızı):</strong></p>
<ul>
<li><p>OR: 1.040 (Risk artırıcı).</p></li>
<li><p>P-Value: &lt; 0.001 (anlamlı).</p></li>
<li><p><strong>Yorum:</strong> Maksimum kalp hızı bağımlı değişken üzerinde istatistiksel olarak anlamlı bir risk artırıcı etkiye sahip.</p></li>
</ul></li>
<li><p><strong>caa_log (Koroner Arter Sayısı - Logaritmik):</strong></p>
<ul>
<li><p>OR: 0.763 (Risk azaltıcı).</p></li>
<li><p>P-Value: &lt; 0.001 ( anlamlı).</p></li>
<li><p><strong>Yorum:</strong> Koroner arter sayısı, bağımlı değişken üzerinde anlamlı şekilde risk azaltıcı bir etkiye sahip.</p></li>
</ul></li>
</ol>
</section>
<section id="genel-risk-analizi" class="level3">
<h3 class="anchored" data-anchor-id="genel-risk-analizi"><strong>Genel Risk Analizi</strong></h3>
<ul>
<li><p><strong>Anlamlı değişkenler</strong>:</p>
<ul>
<li><p><strong>sex</strong>: Kadınlar erkeklere göre %85.6 daha düşük riske sahiptir (odds oranı 0.1439).</p></li>
<li><p><strong>cp_log</strong>: Göğüs ağrısı türü riski %33.4 artırır (odds oranı 1.3344).</p></li>
<li><p><strong>trtbps</strong>: Kan basıncı arttıkça risk %2.8 azalır (odds oranı 0.9717).</p></li>
<li><p><strong>thalachh</strong>: Maksimum kalp hızı arttıkça risk %4.0 artar (odds oranı 1.0402).</p></li>
<li><p><strong>caa_log</strong>: Koroner arter hastalığı arttıkça risk %23.7 azalır (odds oranı 0.7631).</p></li>
<li><p><strong>restecg</strong>: Elektrokardiyogram sonucu risk %32.7 artar (odds oranı 1.3268).</p></li>
</ul></li>
<li><p><strong>Anlamlı olmayan değişkenler</strong>:</p>
<ul>
<li><p><strong>age</strong>: Yaş arttıkça risk %1.3 artar (odds oranı 1.0126), ancak anlamlı değil.</p></li>
<li><p><strong>chol_log</strong>: Kolesterol arttıkça risk %81.3 azalır (odds oranı 0.1868), ancak anlamlı değil.</p></li>
<li><p><strong>fbs</strong>: Açlık kan şekeri arttıkça risk %14.3 artar (odds oranı 1.1433), ancak anlamlı değil.</p></li>
</ul></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>